version = 1

[[annotations]]
path = [
    ".gitignore",
    "Cargo.lock",
    "Cargo.toml"
]
SPDX-FileCopyrightText = "© 2025 Iverson Briones <ivercoder@proton.me>"
SPDX-License-Identifier = "CC0-1.0"